// Pulls the Lucide icons the app uses out of the Iconify icon-sets repo and
// writes them to public/icons.js, so the app ships only the handful it needs
// (no icon font, no runtime CDN requests). Re-run to add icons: npm run icons:extract
//
// Source: https://github.com/iconify/icon-sets (json/lucide.json), Lucide is ISC licensed.
import { writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const SOURCE = "https://raw.githubusercontent.com/iconify/icon-sets/master/json/lucide.json";
const ICONS = [
  "heart", "circle-check", "settings-2", "plus", "check", "rotate-ccw", "trash-2",
  "external-link", "bell", "bell-ring", "bell-off", "send", "user-round", "log-out",
  "sparkles", "leaf", "clock", "flame", "siren", "lock", "x", "key-round", "party-popper",
  "plane", "armchair", "map-pin", "users-round", "list-checks",
];

const res = await fetch(SOURCE);
if (!res.ok) throw new Error(`fetch failed: ${res.status}`);
const set = await res.json();

const out = {};
for (const name of ICONS) {
  const icon = set.icons[name] ?? set.icons[set.aliases?.[name]?.parent];
  if (!icon) throw new Error(`icon not found in ${set.prefix}: ${name}`);
  out[name] = icon.body;
}

const file = join(dirname(fileURLToPath(import.meta.url)), "..", "public", "icons.js");
mkdirSync(dirname(file), { recursive: true });
writeFileSync(
  file,
  `// Generated by scripts/extract-icons.js. Lucide icons (ISC) via https://github.com/iconify/icon-sets\n` +
    `const BODIES = ${JSON.stringify(out, null, 2)};\n\n` +
    `/** Returns an inline SVG for a Lucide icon; size in px (defaults to 1em). */\n` +
    `export function icon(name, size = "1em", extraClass = "") {\n` +
    `  const body = BODIES[name];\n` +
    `  if (!body) { console.warn("unknown icon", name); return ""; }\n` +
    `  return \`<svg class="ic \${extraClass}" width="\${size}" height="\${size}" viewBox="0 0 24 24" aria-hidden="true" focusable="false">\${body}</svg>\`;\n` +
    `}\n\n` +
    `/** Replaces every <i data-icon="name" data-size="22"> placeholder with its SVG. */\n` +
    `export function mountIcons(root = document) {\n` +
    `  for (const el of root.querySelectorAll("i[data-icon]")) {\n` +
    `    el.outerHTML = icon(el.dataset.icon, el.dataset.size ? \`\${el.dataset.size}px\` : "1em", el.className);\n` +
    `  }\n` +
    `}\n\n` +
    `export const ICON_NAMES = Object.keys(BODIES);\n`
);
console.log(`wrote ${file} with ${ICONS.length} icons from ${set.info.name} (${set.info.license.spdx})`);
